using System.ComponentModel;

namespace StansAssets.IOS.XCode
{
    /// <summary>
    /// XCode available project libraries.
    /// </summary>
    public enum XCodeLibraryName
    {
#if !UNITY_WSA
        [Description("CarrierBundleUtilities.tbd")]
        CarrierBundleUtilities,
        [Description("IOABPLib.tbd")]
        IOABPLib,
        [Description("libAccessibility.tbd")]
        libAccessibility,
        [Description("libacmobileshim.tbd")]
        libacmobileshim,
        [Description("libafc.tbd")]
        libafc,
        [Description("libamsupport.tbd")]
        libamsupport,
        [Description("libAppPatch.tbd")]
        libAppPatch,
        [Description("libarchive.2.tbd")]
        libarchive2,
        [Description("libarchive.tbd")]
        libarchive,
        [Description("libARI.tbd")]
        libARI,
        [Description("libARIServer.tbd")]
        libARIServer,
        [Description("libassertion_launchd.tbd")]
        libassertion_launchd,
        [Description("libate.tbd")]
        libate,
        [Description("libauthinstall.tbd")]
        libauthinstall,
        [Description("libAWDProtobufBluetooth.tbd")]
        libAWDProtobufBluetooth,
        [Description("libAWDProtobufFacetime.tbd")]
        libAWDProtobufFacetime,
        [Description("libAWDProtobufFacetimeiMessage.tbd")]
        libAWDProtobufFacetimeiMessage,
        [Description("libAWDProtobufGCK.tbd")]
        libAWDProtobufGCK,
        [Description("libAWDProtobufLocation.tbd")]
        libAWDProtobufLocation,
        [Description("libAWDSupport.tbd")]
        libAWDSupport,
        [Description("libAWDSupportFramework.tbd")]
        libAWDSupportFramework,
        [Description("libAXSafeCategoryBundle.tbd")]
        libAXSafeCategoryBundle,
        [Description("libAXSpeechManager.tbd")]
        libAXSpeechManager,
        [Description("libBasebandManager.tbd")]
        libBasebandManager,
        [Description("libBasebandUSB.tbd")]
        libBasebandUSB,
        [Description("libbsm.0.tbd")]
        libbsm0,
        [Description("libbsm.tbd")]
        libbsm,
        [Description("libbz2.1.0.tbd")]
        libbz210,
        [Description("libbz2.tbd")]
        libbz2,
        [Description("libc++.1.tbd")]
        libcPlusPlus1,
        [Description("libc++.tbd")]
        libcPlusPlus,
        [Description("libc++abi.tbd")]
        libcPlusPlusAbi,
        [Description("libc.tbd")]
        libc,
        [Description("libcharset.1.0.0.tbd")]
        libcharset100,
        [Description("libcharset.1.tbd")]
        libcharset1,
        [Description("libcharset.tbd")]
        libcharset,
        [Description("libChineseTokenizer.tbd")]
        libChineseTokenizer,
        [Description("libcmph.tbd")]
        libcmph,
        [Description("libcompression.tbd")]
        libcompression,
        [Description("libcoretls.tbd")]
        libcoretls,
        [Description("libcoretls_cfhelpers.tbd")]
        libcoretls_cfhelpers,
        [Description("libCRFSuite.tbd")]
        libCRFSuite,
        [Description("libCRFSuite0.12.tbd")]
        libCRFSuite012,
        [Description("libCTLogHelper.tbd")]
        libCTLogHelper,
        [Description("libcupolicy.tbd")]
        libcupolicy,
        [Description("libcurses.tbd")]
        libcurses,
        [Description("libdbm.tbd")]
        libdbm,
        [Description("libDHCPServer.A.tbd")]
        libDHCPServerA,
        [Description("libDHCPServer.tbd")]
        libDHCPServer,
        [Description("libdl.tbd")]
        libdl,
        [Description("libdns_services.tbd")]
        libdns_services,
        [Description("libdscsym.tbd")]
        libdscsym,
        [Description("libedit.2.tbd")]
        libedit2,
        [Description("libedit.3.0.tbd")]
        libedit30,
        [Description("libedit.3.tbd")]
        libedit3,
        [Description("libedit.tbd")]
        libedit,
        [Description("libenergytrace.tbd")]
        libenergytrace,
        [Description("libETLDIAGLoggingDynamic.tbd")]
        libETLDIAGLoggingDynamic,
        [Description("libETLDLFDynamic.tbd")]
        libETLDLFDynamic,
        [Description("libETLDLOADCoreDumpDynamic.tbd")]
        libETLDLOADCoreDumpDynamic,
        [Description("libETLDLOADDynamic.tbd")]
        libETLDLOADDynamic,
        [Description("libETLDMCDynamic.tbd")]
        libETLDMCDynamic,
        [Description("libETLDynamic.tbd")]
        libETLDynamic,
        [Description("libETLEFSDumpDynamic.tbd")]
        libETLEFSDumpDynamic,
        [Description("libETLSAHDynamic.tbd")]
        libETLSAHDynamic,
        [Description("libETLTransportDynamic.tbd")]
        libETLTransportDynamic,
        [Description("libexslt.0.tbd")]
        libexslt0,
        [Description("libexslt.tbd")]
        libexslt,
        [Description("libextension.tbd")]
        libextension,
        [Description("libform.5.4.tbd")]
        libform54,
        [Description("libform.tbd")]
        libform,
        [Description("libgcc_s.1.tbd")]
        libgcc_s1,
        [Description("libgermantok.tbd")]
        libgermantok,
        [Description("libH5Dynamic.tbd")]
        libH5Dynamic,
        [Description("libHDLCDynamic.tbd")]
        libHDLCDynamic,
        [Description("libheimdal-asn1.tbd")]
        libheimdal_asn1,
        [Description("libiconv.2.4.0.tbd")]
        libiconv240,
        [Description("libiconv.2.tbd")]
        libiconv2,
        [Description("libiconv.tbd")]
        libiconv,
        [Description("libicucore.A.tbd")]
        libicucoreA,
        [Description("libicucore.tbd")]
        libicucore,
        [Description("libInFieldCollection.tbd")]
        libInFieldCollection,
        [Description("libinfo.tbd")]
        libinfo,
        [Description("libIOAccessoryManager.tbd")]
        libIOAccessoryManager,
        [Description("libipconfig.tbd")]
        libipconfig,
        [Description("libipsec.A.tbd")]
        libipsecA,
        [Description("libipsec.tbd")]
        libipsec,
        [Description("libktrace.tbd")]
        libktrace,
        [Description("liblangid.tbd")]
        liblangid,
        [Description("libLLVM-C.tbd")]
        libLLVM_C,
        [Description("libLLVM.tbd")]
        libLLVM,
        [Description("liblockdown.tbd")]
        liblockdown,
        [Description("liblizma.5.tbd")]
        liblizma5,
        [Description("liblizma.tbd")]
        liblizma,
        [Description("libm.tbd")]
        libm,
        [Description("libmarisa.tbd")]
        libmarisa,
        [Description("libMatch.1.tbd")]
        libMatch1,
        [Description("libMatch.tbd")]
        libMatch,
        [Description("libmav_ipc_router_dynamic.tbd")]
        libmav_ipc_router_dynamic,
        [Description("libmecab_em.tbd")]
        libmecab_em,
        [Description("libmecabra.tbd")]
        libmecabra,
        [Description("libmis.tbd")]
        libmis,
        [Description("libMobileCheckpoint.tbd")]
        libMobileCheckpoint,
        [Description("libMobileGestalt.tbd")]
        libMobileGestalt,
        [Description("libMobileGestaltExtensions.tbd")]
        libMobileGestaltExtensions,
        [Description("libncurses.5.4.tbd")]
        libncurses54,
        [Description("libncurses.tbd")]
        libncurses,
        [Description("libnetwork.tbd")]
        libnework,
        [Description("libnfshared.tbd")]
        libnfshared,
        [Description("libobjc.A.tbd")]
        libobjcA,
        [Description("libobjc.tbd")]
        libobjc,
        [Description("libomadm.tbd")]
        libomadm,
        [Description("libPCITransport.tbd")]
        libPCITransport,
        [Description("libpoll.tbd")]
        libpoll,
        [Description("libPPM.tbd")]
        libPPM,
        [Description("libprequelite.tbd")]
        libprequelite,
        [Description("libproc.tbd")]
        libproc,
        [Description("libprotobuf.tbd")]
        libprotobuf,
        [Description("libpthead.tbd")]
        libpthead,
        [Description("libQLCharts.tbd")]
        libQLCharts,
        [Description("libresolv.9.tbd")]
        libresolv9,
        [Description("libresolv.tbd")]
        libresolv,
        [Description("librpcsvc.tbd")]
        librpcsvc,
        [Description("libsandbox.1.tbd")]
        libsandbox1,
        [Description("libsandbox.tbd")]
        libsandbox,
        [Description("libsp.tbd")]
        libsp,
        [Description("libspindump.tbd")]
        libspindump,
        [Description("libsqlite3.0.tbd")]
        libsqlite30,
        [Description("libsqlite3.tbd")]
        libsqlite3,
        [Description("libstdc++.6.0.9.tbd")]
        libstdcPlusPlus_609,
        [Description("libstdc++.6.tbd")]
        libstdcPlusPlus_6,
        [Description("libstdc++.tbd")]
        libstdcPlusPlus,
        [Description("libsysdiagnose.tbd")]
        libsysdiagnose,
        [Description("libSystem.B.tbd")]
        libSystemB,
        [Description("libSystem.tbd")]
        libSystem,
        [Description("libsystemstats.tbd")]
        libsystemstats,
        [Description("libtailspin.tbd")]
        libtailspin,
        [Description("libTelephonyBasebandBulkUSBDynamic.tbd")]
        libTelephonyBasebandBulkUSBDynamic,
        [Description("libTelephonyBasebandDynamic.tbd")]
        libTelephonyBasebandDynamic,
        [Description("libTelephonyDebugDynamic.tbd")]
        libTelephonyDebugDynamic,
        [Description("libTelephonyIOKitDynamic.tbd")]
        libTelephonyIOKitDynamic,
        [Description("libTelephonyUSBDynamic.tbd")]
        libTelephonyUSBDynamic,
        [Description("libTelephonyUtilDynamic.tbd")]
        libTelephonyUtilDynamic,
        [Description("libThaiTokenizer.tbd")]
        libThaiTokenizer,
        [Description("libtidy.A.tbd")]
        libtidyA,
        [Description("libtidy.tbd")]
        libtidy,
        [Description("libzupdate.tbd")]
        libzupdate,
        [Description("libutil.tbd")]
        libutil,
        [Description("libutil1.0.tbd")]
        libutil_10,
        [Description("libWAPI.tbd")]
        libWAPI,
        [Description("libxml2.2.tbd")]
        libxlm22,
        [Description("libxml2.tbd")]
        libxml2,
        [Description("libxslt.1.tbd")]
        libxslt1,
        [Description("libxslt.tbd")]
        libxslt,
        [Description("libz.1.1.3.tbd")]
        libz113,
        [Description("libz.1.2.5.tbd")]
        libz125,
        [Description("libz.1.2.8.tbd")]
        libz128,
        [Description("libz.1.tbd")]
        libz1,
        [Description("libz.tbd")]
        libz
#endif
    }
}
